import { Pro, ProCategory, ProStatus, SubscriptionType, Product } from "@golfeexpress/types";

/**
 * Données de démonstration reprenant les commerçants de la maquette
 * golfeexpress_client.html. À remplacer par un appel API (GET /pros) une
 * fois le backend branché — la forme respecte déjà le type `Pro`.
 */

export interface ProWithUi extends Pro {
  emoji: string;
  gradientFrom: string;
  gradientTo: string;
  isOpen: boolean;
  distanceKm: number;
  estimatedMinMinutes: number;
  estimatedMaxMinutes: number;
  tags: string[];
  minOrder: number;
  deliveryFeeDisplay: number;
}

export const MOCK_PROS: ProWithUi[] = [
  {
    id: "pro-poke-paradise",
    userId: "user-poke-paradise",
    businessName: "Poke Paradise",
    siret: "00000000000001",
    description: "Poke bowls frais, healthy, végé",
    category: ProCategory.RESTAURANT,
    logo: null,
    coverImage: null,
    phone: "0494000001",
    emailContact: "contact@pokeparadise.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.PREMIUM,
    rating: 4.8,
    ratingCount: 312,
    createdAt: new Date().toISOString(),
    emoji: "🍣",
    gradientFrom: "#FF8C5A",
    gradientTo: "#FF6B35",
    isOpen: true,
    distanceKm: 1.2,
    estimatedMinMinutes: 25,
    estimatedMaxMinutes: 35,
    tags: ["Poke bowl", "Healthy", "Végé"],
    minOrder: 15,
    deliveryFeeDisplay: 2.9,
  },
  {
    id: "pro-boucherie-port",
    userId: "user-boucherie-port",
    businessName: "Boucherie du Port",
    siret: "00000000000002",
    description: "Viande et charcuterie locale",
    category: ProCategory.BOUCHERIE,
    logo: null,
    coverImage: null,
    phone: "0494000002",
    emailContact: "contact@boucherie-port.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.FREE,
    rating: 4.9,
    ratingCount: 187,
    createdAt: new Date().toISOString(),
    emoji: "🥩",
    gradientFrom: "#8B4513",
    gradientTo: "#A0522D",
    isOpen: true,
    distanceKm: 1.5,
    estimatedMinMinutes: 30,
    estimatedMaxMinutes: 45,
    tags: ["Viande", "Charcuterie"],
    minOrder: 25,
    deliveryFeeDisplay: 3.5,
  },
  {
    id: "pro-parfumerie-soleil",
    userId: "user-parfumerie-soleil",
    businessName: "Parfumerie Soleil",
    siret: "00000000000003",
    description: "Parfums et soins",
    category: ProCategory.PARFUMERIE,
    logo: null,
    coverImage: null,
    phone: "0494000003",
    emailContact: "contact@parfumerie-soleil.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.FREE,
    rating: 4.7,
    ratingCount: 94,
    createdAt: new Date().toISOString(),
    emoji: "🧴",
    gradientFrom: "#FF69B4",
    gradientTo: "#FFB6C1",
    isOpen: true,
    distanceKm: 0.6,
    estimatedMinMinutes: 20,
    estimatedMaxMinutes: 30,
    tags: ["Parfums", "Soins"],
    minOrder: 20,
    deliveryFeeDisplay: 1.9,
  },
];

export const MOCK_NEARBY: ProWithUi[] = [
  {
    id: "pro-fleuriste-riviera",
    userId: "user-fleuriste-riviera",
    businessName: "Fleuriste Riviera",
    siret: "00000000000004",
    category: ProCategory.FLEURISTE,
    description: "Fleurs & Plantes",
    logo: null,
    coverImage: null,
    phone: "0494000004",
    emailContact: "contact@fleuriste-riviera.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.FREE,
    rating: 4.9,
    ratingCount: 56,
    createdAt: new Date().toISOString(),
    emoji: "💐",
    gradientFrom: "#2ECC71",
    gradientTo: "#27AE60",
    isOpen: true,
    distanceKm: 0.8,
    estimatedMinMinutes: 15,
    estimatedMaxMinutes: 25,
    tags: ["Fleurs", "Plantes"],
    minOrder: 0,
    deliveryFeeDisplay: 2.5,
  },
  {
    id: "pro-pharmacie-golfe",
    userId: "user-pharmacie-golfe",
    businessName: "Pharmacie du Golfe",
    siret: "00000000000005",
    category: ProCategory.PHARMACIE,
    description: "Santé & Bien-être",
    logo: null,
    coverImage: null,
    phone: "0494000005",
    emailContact: "contact@pharmacie-golfe.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.FREE,
    rating: 4.6,
    ratingCount: 121,
    createdAt: new Date().toISOString(),
    emoji: "💊",
    gradientFrom: "#4CAF50",
    gradientTo: "#66BB6A",
    isOpen: true,
    distanceKm: 1.2,
    estimatedMinMinutes: 10,
    estimatedMaxMinutes: 20,
    tags: ["Santé"],
    minOrder: 0,
    deliveryFeeDisplay: 1.9,
  },
  {
    id: "pro-librairie-marine",
    userId: "user-librairie-marine",
    businessName: "Librairie Marine",
    siret: "00000000000006",
    category: ProCategory.LIBRAIRIE,
    description: "Livres & Papeterie",
    logo: null,
    coverImage: null,
    phone: "0494000006",
    emailContact: "contact@librairie-marine.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.FREE,
    rating: 4.8,
    ratingCount: 43,
    createdAt: new Date().toISOString(),
    emoji: "📚",
    gradientFrom: "#2196F3",
    gradientTo: "#42A5F5",
    isOpen: true,
    distanceKm: 1.5,
    estimatedMinMinutes: 20,
    estimatedMaxMinutes: 30,
    tags: ["Livres"],
    minOrder: 0,
    deliveryFeeDisplay: 2.0,
  },
  {
    id: "pro-boulangerie-maxime",
    userId: "user-boulangerie-maxime",
    businessName: "Boulangerie Maxime",
    siret: "00000000000007",
    category: ProCategory.BOULANGERIE,
    description: "Boulangerie & Pâtisserie",
    logo: null,
    coverImage: null,
    phone: "0494000007",
    emailContact: "contact@boulangerie-maxime.fr",
    status: ProStatus.ACTIVE,
    commissionRate: 0.15,
    subscriptionType: SubscriptionType.FREE,
    rating: 4.7,
    ratingCount: 88,
    createdAt: new Date().toISOString(),
    emoji: "🥖",
    gradientFrom: "#FF9800",
    gradientTo: "#FFB74D",
    isOpen: true,
    distanceKm: 0.5,
    estimatedMinMinutes: 15,
    estimatedMaxMinutes: 25,
    tags: ["Boulangerie"],
    minOrder: 0,
    deliveryFeeDisplay: 1.9,
  },
];

export const MOCK_PRODUCTS_BY_PRO: Record<string, Product[]> = {
  "pro-poke-paradise": [
    {
      id: "prod-poke-saumon",
      proId: "pro-poke-paradise",
      name: "Poke Saumon",
      description: "Saumon frais, avocat, edamame, riz vinaigré, sauce soja",
      price: 14.9,
      image: "🍣",
      category: "Poke Bowls",
      isAvailable: true,
      isFeatured: true,
    },
    {
      id: "prod-poke-thon",
      proId: "pro-poke-paradise",
      name: "Poke Thon",
      description: "Thon rouge, mangue, concombre, sésame, sauce épicée",
      price: 15.9,
      image: "🐟",
      category: "Poke Bowls",
      isAvailable: true,
      isFeatured: false,
    },
    {
      id: "prod-poke-vege",
      proId: "pro-poke-paradise",
      name: "Poke Végétarien",
      description: "Tofu mariné, avocat, edamame, radis, sauce tahini",
      price: 12.9,
      image: "🥑",
      category: "Poke Bowls",
      isAvailable: true,
      isFeatured: false,
    },
    {
      id: "prod-bubble-tea",
      proId: "pro-poke-paradise",
      name: "Bubble Tea",
      description: "Thé vert, perles de tapioca, lait",
      price: 5.5,
      image: "🧋",
      category: "Boissons",
      isAvailable: true,
      isFeatured: false,
    },
  ],
};
